#!/usr/bin/python

import configobj
import ldap
import cyruslib
import argparse
import sys

def unbind():
    l.unbind_s()

def fatal(message):
    print message
    unbind()
    sys.exit(1)

def clean_exit(message):
    print message
    unbind()
    sys.exit(0)

def main():

    parser = argparse.ArgumentParser()
    parser.add_argument('-c', '--config', help='Use specified config file (default: cyrus-ldap-sync.conf')
    parser.add_argument('-n', '--dry-run', help='Simulate run, do not do anything real', action='store_true')
    parser.add_argument('-s', '--setquota', help='Set quota with SIZE for specified user', metavar='SIZE')
    parser.add_argument('-u', '--username', help='Username for quota modification')

    args = parser.parse_args()

    # load config
    if not args.config:
        conffile = 'cyrus-ldap-sync.conf'
    else:
        conffile = args.config
    config = configobj.ConfigObj(conffile)

    global l
    l = ldap.initialize(config['ldap_uri'])
    imap = cyruslib.CYRUS(config['imap_uri'])

    # bind to ldap server
    l.simple_bind_s(config['bind_dn'], config['bind_pass'])

    # get all CN's of users with mail atrtribute
    r = l.search_s(config['base_dn'], ldap.SCOPE_SUBTREE, '(mail=*)', ['cn'])

    # login to cyrus
    try:
        imap.login(config['cyrus_admin'], config['cyrus_pass'])
    except cyruslib.CYRUSError, e:
        print "%s: %s" % (e[1], e[2])

    if args.setquota:
        if not args.username:
            fatal('--setquota requires --username')
        if not args.dry_run:
            try:
                print 'setting new quota for user: %s' % args.username
                imap.sq("user." + args.username, args.setquota)
            except cyruslib.CYRUSError, e:
                print "%s: %s" % (e[1], e[2])
        q = imap.lq("user." + args.username)
        clean_exit('new quota usage: %d/%d' % q)

    # create accounts for all users
    ulist = []
    for dn, entry in r:
        u = entry['cn'][0]
        try:
            print '\nlooking for mailbox of user: %s' % u
            m = imap.lm("user." + u)
            if len(m) == 0:
                print 'creating mailbox user.%s' % u
                if not args.dry_run:
                    imap.cm("user." + u)
            # get/set quota
            try:
                q = imap.lq("user." + u)
            except cyruslib.CYRUSError, e:
                # if no quota, create it
                if e[0] == 45:
                    print 'creating quota for user: %s' % u
                    if not args.dry_run:
                        imap.sq("user." + u, config['mailbox_quota'])
            else:
                print 'quota usage: %d/%d' % q
                if q[0] > q[1]:
                    print 'Warning: quota limit is reached'
        except cyruslib.CYRUSError, e:
            print "%s: %s" % (e[1], e[2])
        # additionally, form uid list
        ulist.append(u)

    # list all user mailboxes
    umboxlist = imap.lm('user.*')
    # look whether mbox have corresponding ldap user or not
    for mbox in umboxlist:
        if mbox.count('.') < 2:
            mbox_u = mbox.split('.')[1]
            if mbox_u not in ulist:
                try:
                    print 'deleting mailbox of user: %s' % mbox
                    if not args.dry_run:
                        imap.dm(mbox)
                except cyruslib.CYRUSError, e:
                    print "%s: %s" % (e[1], e[2])

if __name__ == '__main__':
    main()
